package com.developpeuseoc.mareu.service;

import com.developpeuseoc.mareu.model.CoWorker;

import java.util.List;

public class FakeApiService implements ApiService{

    private List<CoWorker> coWorkers = FakeApiServiceGenerator.generateCoWorkers();

    /**
     * Return a list of {@link CoWorker}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<CoWorker> getCoWorkers() {
        return coWorkers;
    }

}
